[package]
name = "red-panda"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
dialoguer = "0.11.0"
reqwest = "0.12.5"
scraper = "0.20.0"
serde = "1.0.208"
serde_json = "1.0.125"
tokio = { version = "1.39.2", features = ["full"] }
